#
# Shared Workflows - Docker Build and Push
#
# Reusable Workflows used:
# * Docker Lint
#   * Readme <https://github.com/entur/gha-docker/blob/main/README-lint.md>
#   * Owner: Team Plattform
#   * Slack: #Talk-plattform
# * Docker Build
#   * Readme <https://github.com/entur/gha-docker/blob/main/README-build.md>
#   * Owner: Team Plattform
#   * Slack: #Talk-plattform
# * Docker Push
#   * Readme: <https://github.com/entur/gha-docker/blob/main/README-push.md>
#   * Owner: Team Plattform
#   * Slack: #Talk-plattform
#
# Prerequisites:
#    Appfactory Setup
#
# TODO: This file comes from entur/.github/workflows/ci-docker.yaml
#       Simply delete what you do not need. This file is yours now.
#
name: Docker Build and Push

on:
  pull_request:
    branches:
      - $default-branch

jobs:
  docker-lint:
    name: Docker Lint
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: Dockerfile
  docker-build:
    name: Build Docker Image
    needs: docker-lint
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      dockerfile: Dockerfile
  docker-push:
    name: Push Docker Image
    needs: docker-build
    uses: entur/gha-docker/.github/workflows/push.yml@v1