name: Push
on:
  push:
    branches:
      - main

jobs:
  gradle-build: # https://github.com/actions/starter-workflows/blob/main/ci/gradle.yml
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cd4b95f1dffd155d6d8f6b8c195a3ff2f9f77a5d # v4.4.2
      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          ARTIFACTORY_AUTH_USER: ${{ secrets.ARTIFACTORY_AUTH_USER }}
          ARTIFACTORY_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      - name: Archive Build Artifacts
        if: success()
        uses: actions/upload-artifact@v5
        with:
          name: app
          path: build/libs
          retention-days: 1
          overwrite: true
  docker-build:
    needs: gradle-build
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: app
      build_artifact_path: build/libs
  docker-push:
    needs: docker-build
    uses: entur/gha-docker/.github/workflows/push.yml@v1
