#
# Shared Workflows - CodeQL Scan
#
# Reusable Workflows used:
# * Verify Artifactory Credentials
#   * Readme <https://github.com/entur/gha-security/blob/main/README-code-scan.md>
#   * Owner: Team Plattform
#   * Slack: #talk-plattform
#
# TODO: This file comes from entur/.github/workflow-templates/verify-jfrog-credentials.yml
#       Adopt to your needs, this file is yours now.
#
# Use this if you are unsure if the Artifactory credentials are correct.
#
name: Verify Artifactory Credentials

on:
  workflow_call:

jobs:
  verify-credentials:
    name: Verify Artifactory Credentials
    uses: entur/gha-artifactory/.github/workflows/verify_credentials.yml@v1
    secrets: inherit
